---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudpulse
  labels:
    app.kubernetes.io/name: cloudpulse
    app.kubernetes.io/part-of: cloudpulse
    app.kubernetes.io/managed-by: flux
    environment: production
